// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo7zZ0qahQ2zKmZ_sWdKLbMs0bF51tBQ0',
    appId: '1:44572289304:web:47120cc5790b8d59e3566d',
    messagingSenderId: '44572289304',
    projectId: 'open-ai-chatgpt',
    authDomain: 'open-ai-chatgpt.firebaseapp.com',
    storageBucket: 'open-ai-chatgpt.appspot.com',
    measurementId: 'G-LPPVWZ5R34',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT_GU2aMB9_MIOfgRndBkyhnW9MhtZtM8',
    appId: '1:44572289304:android:0cdcb853606f8e58e3566d',
    messagingSenderId: '44572289304',
    projectId: 'open-ai-chatgpt',
    storageBucket: 'open-ai-chatgpt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYRMLoi79vmqZiyjBOOxTK3jGVGk5KSzc',
    appId: '1:44572289304:ios:b34017b1704feff0e3566d',
    messagingSenderId: '44572289304',
    projectId: 'open-ai-chatgpt',
    storageBucket: 'open-ai-chatgpt.appspot.com',
    iosBundleId: 'com.example.openAiChatgpt',
  );
}
